java_test(
    name = "parser",
    srcs = ["TestParser.java"],
    size = "small",
    test_class = "monkey.parser.TestParser",
    deps = [
        "//java/monkey/lexer",
        "//java/monkey/ast",
        "//java/monkey/parser",
        "//third_party:junit4",
        "//third_party:truth",
        "//third_party:junitparams",
    ],
)
