package(default_visibility = ["//visibility:public"])

java_library(
    name = "repl",
    srcs = ["Repl.java"],
    deps = [
        "//java/monkey/lexer",
        "//java/monkey/parser",
        "//java/monkey/ast",
        "//java/monkey/evaluator",
        "//java/monkey/object",
    ],
)
