java_test(
    name = "ast",
    srcs = ["TestAst.java"],
    size = "small",
    test_class = "monkey.ast.TestAst",
    deps = [
        "//java/monkey/ast",
        "//java/monkey/lexer",
        "//java/monkey/token",
        "//third_party:junit4",
    ],
)
