java_test(
    name = "lexer",
    srcs = ["TestLexer.java"],
    size = "small",
    test_class = "monkey.lexer.TestLexer",
    deps = [
        "//java/monkey/token",
        "//java/monkey/lexer",
        "//third_party:junit4",
    ],
)
