package(default_visibility = ["//visibility:public"])

java_library(
    name = "evaluator",
    srcs = ["Evaluator.java"],
    deps = [
        "//java/monkey/ast",
        "//java/monkey/object",
    ],
)
