package(default_visibility = ["//visibility:public"])

java_library(
    name = "ast",
    srcs = glob(["*.java"]),
    deps = [
        "//java/monkey/token",
        "//third_party:guava",
    ],
)
