package(default_visibility = ["//visibility:public"])

java_library(
    name = "object",
    srcs = glob(["*.java"]),
    deps = [
        "//java/monkey/ast",
        "//third_party:guava",
    ],
)
