package(default_visibility = ["//visibility:public"])

java_library(
    name = "parser",
    srcs = ["Parser.java"],
    deps = [
        "//java/monkey/token",
        "//java/monkey/lexer",
        "//java/monkey/ast",
    ],
)

